language: node_js
node_js:
  - '10.13.0'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - cd server
  - yarn install
  - cd ../frontend
  - yarn install
  - cd ..
  - yarn global add jest
script:
  - yarn test
