export default [
    {level: 0, label: "Assistant"},
    {level: 0, label: "Junior Manager"},
    {level: 0, label: "Manager"},
    {level: 0, label: "Analyst"},
    {level: 0, label: "Category Manager"},
    {level: 0, label: "Category Director"},
    {level: 0, label: "Senior Manager"},
    {level: 0, label: "Performance"},
    {level: 0, label: "Director"},
    {level: 0, label: "Head of"},
    {level: 0, label: "Head of Excellence"},
    {level: 0, label: "Head of Indirect"},
    {level: 0, label: "Head of Direct"},
    {level: 0, label: "VP"},
    {level: 0, label: "SVP"},
    {level: 0, label: "CPO"},
    {level: 0, label: "Global CPO"},
    {level: 0, label: "C-Level"},
    {level: 0, label: "Consultant"},
    {level: 0, label: "Partner"},
    {level: 0, label: "Lecturer"},
    {level: 0, label: "Student"},
    {level: 0, label: "Journalist"},
    {level: 0, label: "Buyer"}
]